import { hasLegacyDocumentIdentity, type CurriculumOverrides } from "./curriculum";
import type { LearnerState } from "./types";

/**
 * Legacy-identity quarantine.
 *
 * Milestone 2 derived a document id from a hash taken after pdfjs had already
 * detached the buffer, so every upload produced the same short identity. Two
 * unrelated PDFs could therefore share concept ids — and with them approvals,
 * edits and learner progress.
 *
 * Returning those concepts to DRAFT is not enough: the mastery, attempts, FSRS
 * schedule and completion recorded against the colliding ids may belong to a
 * different document entirely. None of it can be trusted, so it is removed.
 * Authored Milestone 1 progress is untouched — its ids never collided.
 */

export interface QuarantineResult {
  learner: LearnerState;
  quarantinedConceptIds: string[];
  quarantinedChunkIds: string[];
  quarantinedLectureIds: string[];
  /**
   * True when anything was actually removed.
   *
   * Callers persist on this, not on the concept list: legacy state can consist
   * of nothing but chunk, lecture and interleaving bookkeeping, with no
   * progress record at all. Keying persistence off concepts alone cleaned that
   * state in memory and let the unsafe version return on the next reload.
   */
  changed: boolean;
}

/** Ingested documents whose identity was generated by the broken hash. */
export function legacyDocumentIds(overrides: CurriculumOverrides): Set<string> {
  const ids = new Set<string>();
  for (const entry of overrides.ingested) {
    if (hasLegacyDocumentIdentity(entry.document.id)) ids.add(entry.document.id);
  }
  for (const concept of overrides.concepts) {
    if (hasLegacyDocumentIdentity(concept.source.documentId)) {
      ids.add(concept.source.documentId);
    }
  }
  return ids;
}

export function hasLegacyIdentities(overrides: CurriculumOverrides): boolean {
  return legacyDocumentIds(overrides).size > 0;
}

/**
 * Strip every learner record that hangs off an untrusted document identity.
 *
 * Pure: returns a new LearnerState and reports what it removed so the caller
 * can tell the learner why their progress on that material is gone.
 */
export function quarantineLegacyLearnerState(
  learner: LearnerState,
  overrides: CurriculumOverrides,
): QuarantineResult {
  const legacyDocs = legacyDocumentIds(overrides);
  if (legacyDocs.size === 0) {
    return {
      learner,
      quarantinedConceptIds: [],
      quarantinedChunkIds: [],
      quarantinedLectureIds: [],
      changed: false,
    };
  }

  const conceptIds = new Set(
    overrides.concepts
      .filter((c) => legacyDocs.has(c.source.documentId))
      .map((c) => c.id),
  );

  const chunkIds = new Set<string>();
  const lectureIds = new Set<string>();
  for (const entry of overrides.ingested) {
    for (const chunk of entry.chunks) {
      if (legacyDocs.has(chunk.documentId) || legacyDocs.has(entry.document.id)) {
        chunkIds.add(chunk.id);
        lectureIds.add(entry.lectureId);
      }
    }
  }

  // Track what was actually removed, not what would have been: the count is
  // shown to the learner, so re-running on already-clean state must not claim
  // that more progress was discarded.
  const removedConceptIds: string[] = [];
  const removedChunkIds = new Set<string>();
  const removedLectureIds: string[] = [];

  // Mastery, attempts and FSRS schedule for untrusted concepts.
  const progress: LearnerState["progress"] = {};
  for (const [conceptId, record] of Object.entries(learner.progress)) {
    if (conceptIds.has(conceptId)) {
      removedConceptIds.push(conceptId);
    } else {
      progress[conceptId] = record;
    }
  }

  // Interleaving bookkeeping, both by chunk and by injected concept.
  const injectedByChunk: LearnerState["injectedByChunk"] = {};
  for (const [chunkId, injected] of Object.entries(learner.injectedByChunk)) {
    if (chunkIds.has(chunkId)) {
      removedChunkIds.add(chunkId);
      continue;
    }
    const kept = injected.filter((id) => !conceptIds.has(id));
    if (kept.length !== injected.length) removedChunkIds.add(chunkId);
    if (kept.length > 0) injectedByChunk[chunkId] = kept;
  }

  const taughtChunkIds = learner.taughtChunkIds.filter((id) => {
    if (!chunkIds.has(id)) return true;
    removedChunkIds.add(id);
    return false;
  });
  const completedChunkIds = learner.completedChunkIds.filter((id) => {
    if (!chunkIds.has(id)) return true;
    removedChunkIds.add(id);
    return false;
  });
  // A lecture that contained quarantined material is no longer complete, so it
  // must not keep a later lecture unlocked on its behalf.
  const completedLectureIds = learner.completedLectureIds.filter((id) => {
    if (!lectureIds.has(id)) return true;
    removedLectureIds.push(id);
    return false;
  });

  return {
    learner: {
      ...learner,
      progress,
      taughtChunkIds,
      completedChunkIds,
      completedLectureIds,
      injectedByChunk,
    },
    quarantinedConceptIds: removedConceptIds,
    quarantinedChunkIds: [...removedChunkIds],
    quarantinedLectureIds: removedLectureIds,
    changed:
      removedConceptIds.length > 0 ||
      removedChunkIds.size > 0 ||
      removedLectureIds.length > 0,
  };
}

/**
 * Accept learner state arriving from storage — at hydration, or from another
 * tab through a `storage` event.
 *
 * Both paths go through here so they cannot drift apart: a stale tab holding
 * pre-quarantine state will happily write it back, and re-injecting mastery,
 * attempts, FSRS schedule or completion for an untrusted identity is exactly
 * what the hydration-time quarantine exists to prevent.
 */
export function acceptIncomingLearnerState(
  incoming: LearnerState,
  overrides: CurriculumOverrides | null,
): QuarantineResult {
  if (!overrides) {
    return {
      learner: incoming,
      quarantinedConceptIds: [],
      quarantinedChunkIds: [],
      quarantinedLectureIds: [],
      changed: false,
    };
  }
  return quarantineLegacyLearnerState(incoming, overrides);
}
